# Generated by Django 5.0.4 on 2024-06-23 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='установленный бюджет')),
                ('start_date', models.DateField(verbose_name='начало периода')),
                ('end_date', models.DateField(verbose_name='конец периода')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='login.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
